language: android

jdk:
  - oraclejdk8

android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-m2repository

script:
  - mvn --settings maven.settings.xml license:check checkstyle:check && ./gradlew clean assembleDebug
